dictionary = {
    'notify paths': 'ناوگان را خبر کن',
    'algorithm': 'الگوریتم',
    'evaluate': 'ارزیابی کن',
    'employee': 'کارمند',
    'capacity': 'ظرفیت',
    'action': 'اعمال',
    'result': 'نتیجه',
    '': '',
    'paths download': 'بارگیری مسیرها',
    'clear': 'پاک کردن',
    'vehicles': 'وسایل نقلیه...',
    'average': 'میانگین',
    'total': 'کل',
    'pointed': 'نقطه‌به‌نقطه',
    'in seconds': 'درثانیه',
    'path': 'مسیر',
    'in': 'در',
    'second': 'دومین',
    'seconds': 'ثانیه',
    'upload': 'بارگذاری',
}
